title = "Kyle's"
baseURL = "https://mael.is"
theme = 'ananke'
resourceDir = "./resources"

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 8 # this is set low for demonstrating with dummy content. Set to a higher number

[languages.en]
contentDir = "./content"
languageCode = 'en-US'
weight = 1
title = "Kyle's"
# languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
mainSections = ["posts", "other"]
text_color = ""
author = "Grigory Vakulenchuk" # default author, override via `author` in a posts front matter
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 8

[params.ananke.social.share]
networks = [
  "email",
  "bluesky"
]

[params.ananke.social.follow]
networks = [
  "bluesky",
  "wikipedia"
]

# [params.ananke.social.facebook]
# username = "patrick.kollitsch"
# profilelink = "https://www.facebook.com/patrick.kollitsch"

# [params.ananke.social.facebook]
# username = "patrick.kollitsch"
# profilelink = "https://www.facebook.com/patrick.kollitsch"

# [params.ananke.social.linkedin]
# username = "patrickkollitsch"

# [params.ananke.social.bluesky]
# username = "kollitsch.dev"

# [params.ananke.social.wikipedia]
# username = "Hugo_(software)"

# [params.ananke.social.networks.wikipedia]
# slug = "wikipedia"
# label = "Wikipedia"
# color = "#0645ad"
# profile = "https://en.wikipedia.org/wiki/%s"
# icon = "wikipedia-w"
